version: '3.3'
services:
  lending:
    image: 'lending:1.0'
    build:
      context: ./lending
      dockerfile: dev.dockerfile
    volumes:
      - ./lending:/app
      - /app/node_modules/
    ports:
      - '8888:8888'
